### ISSUE TITLE
Release start/finish functions are not taking any input arguments?

### ISSUE THREAD

**Issue by allanwsilva** [gitex-flow/gitex-flow-node#31]
From what I can see in `src/cli.ts`, in the snippet below:

```
const release = command.command('release');
release.command('start').action(async () => {
  await Utils.exec(() => gFlow.release.start());
});
```

both start/finish functions are not taking arguments, correct?

happy for me to submit a PR?

**Comment by CuddlySheep** [comment]
Thank you very much for your question.

Indeed... Usually I use the command 'gitex-flow release start' without arguments, because the names of releases and hotfixes are automatically calculated by gitex-flow based on the next semantic version. However, the documentation considers these optional arguments. For this reason their absence can be classified as a bug.

Fortunately the framework generally supports user-defined names for release and hotfixes and only needs to be passed through by command line tool.

```
const release = command.command('release');
release.command('start [name]').action(async (name?: string) => {
  await Utils.exec(() => gFlow.release.start(name));
});
```
It would be very nice if this bug could be solved for starting and finishing releases and hotfixes too.
PRs are welcome 👍

**Comment by allanwsilva** [comment]
You were faster than me @CuddlySheep , thanks!
