### ISSUE TITLE
gitflow-avh deprecation

### ISSUE THREAD

**Issue by shaedrich** [gitex-flow/gitex-flow-node#77]
gitflow-avh has been archived on Jun 19, 2023. Do you plan on swapping it out with an alternative implementation (like [gitflow-cjs](https://github.com/CJ-Systems/gitflow-cjs))?

**Comment by jrebmann** [comment]
Thank you for your request.

Actually I was not aware that the project `gitflow-avh` is no longer supported. So thanks for the info.

The good thing is that `gitex-flow` is actually designed to support different implementations of git-flow.

As soon as I get around to it, will have a look at `gitflow-cjs`. It might even not be that hard to migrate.

**Comment by shaedrich** [comment]
Yeah, you're welcome. I found out myself by coincidence ^^

> The good thing is that gitex-flow is actually designed to support different implementations of git-flow.

Sounds great. I have to admit that I found your extension just around the same time. But so far, it works good in VSCode for me.

If you have any questions around `gitflow-cjs` or need assistance, from my experience, its maintainer is quite active and supportive.

**Comment by jrebmann** [comment]
Hi @shaedrich,

I now got around to analyzing the `gitflow-cjs`. The good news is that `gitflow-cjs` is 100% backward compatible with `gitflow-avh`. This means that all functions of `gitex-flow` also work with `gitflow-cjs`.

Unfortunately, there is a bug with the current version `gitflow-cjs` 2.2.0, whereby `gitex-flow` does not work either, because the console output is messy. However, with the previous version 2.1.0 everything works as desired.

I have created a bug report about the gitflow-cjs 2.2.0 version: https://github.com/CJ-Systems/gitflow-cjs/issues/82

**Comment by ChrisJStone** [comment]
> Unfortunately, there is a bug with the current version `gitflow-cjs` 2.2.0, whereby `gitex-flow` does not work either, because the console output is messy. However, with the previous version 2.1.0 everything works as desired.
> 

Could you please provide a screen shot of the messy console output at [CJ-Systems/gitflow-cjs#82](https://github.com/CJ-Systems/gitflow-cjs/issues/82) for comparison as running gitex-flow on my development system appears to produce proper output

![image](https://github.com/gitex-flow/gitex-flow-node/assets/450713/a1c370b0-427a-4615-a9ad-fe24736e0407)
